### ISSUE TITLE
GDAL includes a subset of boost which conflicts with projects which already use boost

### ISSUE THREAD

**Issue by brandon-kohn** [gisinternals/buildsystem#107]
When using one of the pre-built bundles, there is a boost folder in the include directory which includes a subset of the boost libraries. This conflicts with projects which already include boost. I believe that if boost is a dependency of gdal, it should be listed as such in the build requirements with a minimum version. Then users should be made to supply this version.

**Comment by szekerest** [comment]
libkml requires boost as a sub-dependency

**Comment by szekerest** [comment]
boost-1.75.0 was included in the recent SDK
