### ISSUE TITLE
Gdal v2.2.0 build?

### ISSUE THREAD

**Issue by pmeems** [gisinternals/buildsystem#109]
The stable version of GDAL is already on v2.2.0 but on GisInternals.com I can only find v2.1.3: http://gisinternals.com/packageinfo.php?file=release-1800-x64-gdal-2-1-mapserver-7-0.zip#gdalversionDiv
And the development version is v2.3.0: http://gisinternals.com/packageinfo.php?file=release-1800-x64-gdal-mapserver.zip#gdalversionDiv

When will v2.2.0 be available?

**Comment by szekerest** [comment]
fixed
