### ISSUE TITLE
Links to GDAL github commit invalid

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#124]
The github repository is invalid: should be OSGeo/gdal and not gdal/gdal

For example, http://gisinternals.com/status.php has a link to https://github.com/gdal/gdal/commit/1f6fc46e42b62cdc688315df21b695d93e3383be instead of https://github.com/OSGeo/gdal/commit/1f6fc46e42b62cdc688315df21b695d93e3383be

**Comment by szekerest** [comment]
Fixed, thanks.
