### ISSUE TITLE
libpq is not compiled with ssl for the latest stable releases

### ISSUE THREAD

**Issue by AlbertXingZhang** [gisinternals/buildsystem#133]
I'm using "release-1911-x64-gdal-2-3-2-mapserver-7-2-1" published by 2018-10-06 17:38:42.
When I run ogrinfo with a PostreSQL connection string which contains "sslmode=require", I got the following error: `sslmode value "require" invalid when SSL support is not compiled in`

But there is a work around. Just copy libpq.dll from an old release like "release-1911-x64-gdal-2-3-0-mapserver-7-0-7" and it works again.

It is not a big problem since I have a solution for it. I appreciate you provide such great built binary packages. They save me a lot of time and make life easier. Many thanks!

**Comment by szekerest** [comment]
Recompiled libpq. The next builds will contain the fix
