### ISSUE TITLE
GDAL build now requires PROJ master

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#134]
Consequence of https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn now being merged.

**Comment by szekerest** [comment]
@rouault Is this the official location?  https://github.com/OSGeo/proj.4
RFC-73 mentions that libgeotiff master is also required.

**Comment by rouault** [comment]
> Is this the official location? https://github.com/OSGeo/proj.4

Yes

> https://github.com/gisinternals/buildsystem/issues/134#issuecomment-459517105

True. The internal libgeotiff has been updated to libgeotiff master, but if you build against external libgeotiff already, it should be upated to libgeotiff master.

**Comment by szekerest** [comment]
Fixed

**Comment by rouault** [comment]
@szekerest Great ! Is PROJ master refreshed at every build ? It would not be surprising that there are breaking changes until PROJ 6 is released

**Comment by szekerest** [comment]
@rouault proj-master is not refreshed by the daily build at the moment, though it would be possible to implement such change.
