### ISSUE TITLE
Fix sdkshell.bat for GDAL 2.5.0 and Proj6 

### ISSUE THREAD

**Issue by jratike80** [gisinternals/buildsystem#135]
Latest development versions with GDAL 2.5.0-dev are throwing errors

gdal_translate foo.tif bar.tif
Input file size is 12000, 12000
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

For fixing the issue the PROJ_LIB path must be set to point to proj6
SET "PROJ_LIB=%SDK_ROOT%bin\proj6\SHARE"

**Comment by szekerest** [comment]
Already fixed
