### ISSUE TITLE
Update to PROJ 6.0.0

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#137]
PROJ 6.0.0 has been released. Would be good to update to it (or consider doing rolling builds of PROJ master)

**Comment by szekerest** [comment]
Updated to the 6.0 branch? 
Does it make sense to include proj6 in the daily builds (ie. will the code change so frequently)?

**Comment by rouault** [comment]
Thanks.
Depends on what is most convenient for you: continuous updates in daily builds vs upgrading each time a PROJ release is done
