### ISSUE TITLE
Build broken: "PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency"

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#138]
Today (27 april 2019) builds are broken: http://build2.gisinternals.com/sdk/build-output/vc14-20190427-0-47-33-26-vc14-dev-err.txt
```makefile.vc(6) : fatal error U1050: PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency```
PROJ_INCLUDE is indeed missing from http://build2.gisinternals.com/sdk/build-output/vc14-20190427-0-47-33-26-vc14-dev.txt, whereas it was present in http://build2.gisinternals.com/sdk/build-output/vc14-20190426-1-57-14-01-vc14-dev.txt

**Comment by szekerest** [comment]
Fixed

**Comment by Darker** [comment]
I just got this error when building 3.0.1 in Visual Studio 2017.
