### ISSUE TITLE
C# bindings: cannot find proj.db

### ISSUE THREAD

**Issue by Gigas002** [gisinternals/buildsystem#140]
I'm using the 3.0.0.1 [GDAL](https://www.nuget.org/packages/GDAL/) and [GDAL.Native](https://www.nuget.org/packages/GDAL.Native/) nuget packages.
`Gdal.wrapper_GDALBuildVRT_names` method throws some exceptions:

![image](https://user-images.githubusercontent.com/24297712/58945039-ba75d880-878b-11e9-8378-7b858b8b363a.png)

**Comment by boneill81** [comment]
I can verify this. I spent quite some time this morning trying to debug an issue related to this. Also if one manually sets the PROJ_LIB environment variable, it will begin working but the resulting projections are way off. I projected some points from 29903 to 3035 and they were projected way off from their correct locations. I have another machine with gdal-204-1911-x64-core installed and it works just fine.

**Comment by geographika** [comment]
The latest GISInternals build kits use Proj6 which uses a SQLite database(proj.db) for projection codes rather than the old text file - see https://proj.org/news.html#id28

**Comment by szekerest** [comment]
I've unlisted the v3.0.0.x packages from nuget, because proj6 doesn't seem to consider the PROJ_LIB environment setting. I'll reissue the packages as soon as the problem was  fixed.

**Comment by szekerest** [comment]
The recent nuget version (3.4.1) contains the fix to configure the proj.db location.
