### ISSUE TITLE
GEOS library is not complete (errors with QGIS)

### ISSUE THREAD

**Issue by MCA4213** [gisinternals/buildsystem#141]
Hi,
When trying to use your pre-build version of gdal with QGIS, I found some errors with the Geos library:
- GEOSVoronoiDiagram_r and GEOSClipByRect_r was not defined;
- some intersection headers in operations was not found like rectangle.h;
- some algorithms like PointLocation.h was missed;

Is it possible to have a  **full compiled geos** library with all options?
Thanks

**Comment by szekerest** [comment]
Hi,

Which version of GEOS should be used with that Qgis build?
I suspect QGIS wants to use the geos dll-s directly as well.

Best regards,

Tamas


MCA4213 <notifications@github.com> ezt írta (időpont: 2019. júl. 10., Sze,
16:16):

**Comment by MCA4213** [comment]
Hi, 
the version that is actually used is almost enough, it compiles well except for some functionalities where the missing functions and headers.

On the Install file of QGIS it is written geos must be >=3.4; BUT when I checked now, I found that all the functions that I mentioned before are on >=3.5.

**So I think the that a higher version (>=3.5) should solve the problem;**

Thank you very much.

**Comment by szekerest** [comment]
geos - 3.9.0 is included in the recent SDK, closing
