### ISSUE TITLE
Debug linking fail in VS2017 starting from gdal-2-3-3 and higher

### ISSUE THREAD

**Issue by geometrika** [gisinternals/buildsystem#147]
It seems that problem comes from libprotobuf-lite.lib and libprotobuf.lib because they are static libraries not linking to any dll. In gdal-2-2-3 these libraries absent and no problem to build debug version appears. 

I have simple console project that uses gdal.  In release mode everything is ok. But in debug mode linking fails becuase in is not possible to mix static release libraries (libprotobuf-lite.lib and libprotobuf.lib) and code built with debug flags.

**Comment by szekerest** [comment]
We don't intend to provide debug binaries in the future.
