### ISSUE TITLE
GDAL 3.0.2 x64,  Exception: GEOS 3.8 or later needed for MakeValid

### ISSUE THREAD

**Issue by JensKlambauer** [gisinternals/buildsystem#150]
Hallo,
i use "release-1911-x64-gdal-3-0-2-mapserver-7-4-2"

in GDAL 3.x a new function MakeValid() for OGRGeometry
https://gdal.org/doxygen/classOGRGeometry.html#a26664b35c9a65737ccb26a38dc161214
This function is built on the GEOS >= 3.8 library, check it for the definition of the geometry operation.

Is it possible to change this in your new builds?

Thanks

**Comment by JensKlambauer** [comment]
now working
i tested with "release-1928-x64-gdal-3-2-1-mapserver-7-6-2" MSVC 2019, x64
new GEOS libary

Thanks a lot!

**Comment by szekerest** [comment]
great, closing
