### ISSUE TITLE
GDAL core 3.0 with gdal 3.1 python bindings

### ISSUE THREAD

**Issue by ev0065** [gisinternals/buildsystem#155]
I posted this [issue](https://github.com/OSGeo/gdal/issues/2700) and was told to redirect it here. 

Essentially, I need gdal 3.1 and have installed gdal 3.1 python bindings, but I was told that it would not work with gdal 3.0 core. However, there is no gdal 3.1 core release. I would appreciate any help looking into this issue. All of the details are located in the hyperlink above, I figured that it would avoid a long post here. 

Thanks.

**Comment by szekerest** [comment]
3.2 is already available, closing
