### ISSUE TITLE
convert C# bindings to .NET Standard 2.0

### ISSUE THREAD

**Issue by BrannonKing** [gisinternals/buildsystem#157]
Is it possible to make the C# bindings target .NET Standard 2.0 rather than .NET Framework 4.0? That would greatly help my deployment as it moves to .NET Core 3.1. 

An example of other people doing it: https://github.com/MaxRev-Dev/gdal.netcore

Also, it may be valuable to verify that the bindings work on both Windows and Linux. (That should be as easy as leaving the ".dll" portion of the shared library off in the binding code.)

**Comment by szekerest** [comment]
The gdal stable and development builds (for GDAL 3.2.x) now create netstandard versions. Still need to create nuget packages for gdal3

**Comment by szekerest** [comment]
Nuget packages GDAL, GDAL.Native and GDAL.Plugins has already been uploaded (3.4.1)
