### ISSUE TITLE
netcdf_mem.h missing

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#165]
The SDK lacks the NETCDF header netcdf_mem.h that could be used by GDAL (see https://github.com/OSGeo/gdal/pull/3363 + https://github.com/OSGeo/gdal/pull/3363/checks?check_run_id=1676933080)

**Comment by szekerest** [comment]
@rouault The "old" SDK is based on netcdf-4.3.2 which doesn't contain this file. 
The VS2019 builds are based on the new SDK, and I'm going to create the VS2017/15 builds based in this new SDK soon. The "old" SDK is not going to be maintained further.
