### ISSUE TITLE
FITS format support missing

### ISSUE THREAD

**Issue by schizz99** [gisinternals/buildsystem#166]
Latest builds up to release-1928-x64-gdal-3-2-1-mapserver-7-6-2 have FITS listed as a supported format in the included gdal_formats.txt and the required dlls (e.g. cfitsio.dll, gdal_FITS.dll) present, however gdal_translate does not recognize the format and a call to gdalinfo --formats does not list it as supported.

Is there something additional that needs to be enabled to use the included dlls and recognize the format?

**Comment by szekerest** [comment]
@schizz99  Downoaded and unzipped http://download.gisinternals.com/sdk/downloads/release-1928-x64-gdal-3-2-1-mapserver-7-6-2.zip , then opened SDKShell.bat.  gdalinfo --formats reports "FITS -raster,vector- (rw+): Flexible Image Transport System"
![image](https://user-images.githubusercontent.com/1408872/104647200-c63cb700-56b1-11eb-93de-a859d276d6f8.png)

**Comment by schizz99** [comment]
Do you know which portions of that script enable the FITS component? My workplace does not generally allow batch scripts to run.

Setting the PROJ_LIB and GDAL_DATA variables is not enough to make FITS appear on the supported formats list from gdalinfo --formats.

**Comment by geographika** [comment]
@schizz99 probably:

https://github.com/gisinternals/buildsystem/blob/f07ca403cd48c099b7923ef9caece3a1985a47af/SDKShell.bat#L36
