### ISSUE TITLE
OGDI driver cannot load vmap file due to missing vrf dll

### ISSUE THREAD

**Issue by sylvaneau** [gisinternals/buildsystem#168]
Hi,

Once again thank you for the amazing work you've done with integrating OGDI driver in your build.

However there is a small issue, when trying to call ogrinfo on a vmap file, the driver displays the following error :
`Could not find the dynamic library "vrf"`

The problem is due to the fact that the `vrf.dll` is missing. I was able to download it through the OsGeo4W installer (the OGDI package contains the dll).

Can you include this dll in a future release ?

Thx

**Comment by szekerest** [comment]
Thanks @sylvaneau , the next builds will contain the fix.

**Comment by qtran** [comment]
@szekerest when can we expect a new stable release with this fix?

**Comment by szekerest** [comment]
@qtran I thought it was already fixed. However I'm going to create a new release build tomorrow.

**Comment by qtran** [comment]
@szekerest thanks, very much appreciated

**Comment by qtran** [comment]
> @qtran I thought it was already fixed. However I'm going to create a new release build tomorrow.

You are right, I just checked but only in GDAL 3.2.2 and MapServer 7.6.2. I'm using GDAL 2.4.4 and MapServer 7.4.3.

**Comment by szekerest** [comment]
The recent SDK already contains this dll
