### ISSUE TITLE
lti_dsdk_9.5.dll missing for MrSID extension (ERROR 1: Can't load requested DLL: C:\Program Files\GDAL\gdalplugins\gdal_MrSID.dll)

### ISSUE THREAD

**Issue by agiudiceandrea** [gisinternals/buildsystem#169]
It seems that lti_dsdk_9.5.dll, lti_dsdk_cdll_9.5.dll and tbb.dll are needed by the MrSID GDAL plugin to properly work.

I think they should be shipped with the MrSID extension or it should be advised somewhere to install them and how,

```
ERROR 1: Can't load requested DLL: C:\Program Files\GDAL\gdalplugins\gdal_MrSID.dll
126: Impossibile trovare il modulo specificato.
```

As a workaround, extracting the missing dll from the Extensis SDK for Windows (with corresponding Visual Studio version and architecture bit width) available at https://www.extensis.com/support/developers in the `C:\Program Files\GDAL\` folder solves the issue.

This issue is similar to previously reported and already fixed issue https://github.com/gisinternals/buildsystem/issues/129

**Comment by BBoldenow** [comment]
I'm having the same issue, and I even added the DLLs in question (I tried both the GDAL folder and the gdalplugins folder). Has anyone been able to resolve this?

**Comment by szekerest** [comment]
@BBoldenow Thanks for the report, I'll fix this issue in the installer shortly

**Comment by szekerest** [comment]
Packages have now been recreated. Closing this for now.
