### ISSUE TITLE
Empty curl-ca-bundle.crt in latest build packages

### ISSUE THREAD

**Issue by geographika** [gisinternals/buildsystem#171]
The `bin/curl-ca-bundle.crt` contains the following rather than certs:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://curl.se/ca/cacert.pem">here</a>.</p>
<hr>
<address>Apache Server at curl.haxx.se Port 80</address>
</body></html>
```

**Comment by geographika** [comment]
Note this appears to only be the case for the daily dev builds e.g. https://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-mapserver.zip
The stable versions seem to be fine.

**Comment by szekerest** [comment]
I believe this was already fixed.
