### ISSUE TITLE
WIX MapServer Setup Project not working for IIS10

### ISSUE THREAD

**Issue by geographika** [gisinternals/buildsystem#173]
I'm currently looking at updating https://mapserver.org/installation/iis.html and was trying the IIS installer on a new Windows 10 machine. It looks like the comparison at: https://github.com/gisinternals/buildsystem/blob/26ce905e2050cfbec8e2114300de6c56f913e380/wixprojects/mapserver/MapServer.wxs#L125

is using a string comparison so "10" < "7" and when using IIS10 the installer can't continue with the message below:

![image](https://user-images.githubusercontent.com/490840/115704276-77b34e80-a36b-11eb-8cbb-e0da3008a9d2.png)

See https://github.com/wixtoolset/issues/issues/5276 for a similar issue. 
Might just be better to check if there is any version number?

Registry keys:

![image](https://user-images.githubusercontent.com/490840/115704240-6bc78c80-a36b-11eb-8a18-8401366fa0ea.png)

**Comment by szekerest** [comment]
The MapServer installer is considered to be obsolete. I'd prefer to include the IIS registration support into MapManager to provide a separate registration per mapfile.
