### ISSUE TITLE
No core installer for 3.3

### ISSUE THREAD

**Issue by rooby** [gisinternals/buildsystem#176]
There seem to be no core installers for GDAL 3.3.x

For example https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-3-0-mapserver-7-6-3.zip and https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-3-mapserver-7-6.zip have no core installers.

On https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-mapserver.zip, the core installer is 302.

**Comment by rooby** [comment]
Seems like cause of the issue reported in https://github.com/gisinternals/buildsystem/issues/167 might still be happening

**Comment by szekerest** [comment]
Fixed
