### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in ogr_csharp.dll 

### ISSUE THREAD

**Issue by qzhangxy** [gisinternals/buildsystem#182]
An unhandled exception of type 'System.AccessViolationException' occurred in ogr_csharp.dll :

namespace OSGeo.OGR
{
	public class DataSource : IDisposable
...
`public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					OgrPINVOKE.delete_DataSource(swigCPtr);
				}
				**swigCPtr = new HandleRef(null, IntPtr.Zero);**
				GC.SuppressFinalize(this);
			}
		}`

**Comment by qzhangxy** [comment]
swigCPtr = new HandleRef(null, IntPtr.Zero);

**Comment by qzhangxy** [comment]
who can help me? Thanks

**Comment by qzhangxy** [comment]
solved

**Comment by szekerest** [comment]
@qzhangxy What was the problem specifically?
