### ISSUE TITLE
GDAL version numbering?

### ISSUE THREAD

**Issue by BR-dev0** [gisinternals/buildsystem#184]
Is there a reason, that gdalXXX.dll has a different internal and external numbering scheme? 

Current GDAL version is 3.4.0.0. This is reflected in gdal_version.h.in of the current source as well as in the GDAL source release numbering scheme. Current GISInternals stable branch refers partially to GDAL-3-4 (single *.zip; libs; py-bindings) and to GDAL-3-0-4 (core; plugins). The current filename is gdal304.dll in both cases. The internal file version, OTOH, is 3.4.0. 

This difference in numbering can be seen in older GISInternals releases, as well. Is it necessary for compatibility with other programs? It is quite confusing...

**Comment by szekerest** [comment]
As far a I can understand gdal304.dll dll name refers to the 3.4 branch with the option to have 2 digits for the minor release number. I'm not sure about the reason of this scheme, please refer to the gdal-dev list for more details. Closing this issue now.

**Comment by BR-dev0** [comment]
After reading through gdal-dev for the last couple of hours, the file name numbering scheme really _is_ intentional with 1-digit major version number, 2-digit minor version number and no digit for revision number. This seems to have caused confusion several times, already. - So, I'm not the only one affected.  ;-)

Here's an example:
https://lists.osgeo.org/pipermail/gdal-dev/2018-April/048470.html

Even Rouault answered Gil:
| > I tried using gdal2.0.2 (deployed with QGIS 3.0) 
|
| This is the dll name. gdal202 = gdal 2.[0]2. It is actually GDAL 2.2.4

Thank you very much for the explanation and the pointer!
