### ISSUE TITLE
Feature request: FTS5 support in SQLite

### ISSUE THREAD

**Issue by rdewit** [gisinternals/buildsystem#188]
The official builds of [SQLite](https://www.sqlite.org/2022/sqlite-tools-win32-x86-3370200.zip) have [FTS5](https://www.sqlite.org/fts5.html) (full-text search) enabled by default. The GisInternals builds do not. 

How to test:

* run sqlite3.exe
* execute the following SQL: `CREATE VIRTUAL TABLE email USING fts5(sender, title, body)`
* observe the error message: `Error: no such module: fts5`

Is it possible to have future versions of `sqlite3.exe` within GisInternals have FTS5 support?

**Comment by szekerest** [comment]
fts5.dll has now been added.

**Comment by rdewit** [comment]
Thanks so much!

**Comment by rdewit** [comment]
I've just tried out the latest production build and I can get FTS5 to work by loading the extension explicitly (i.e. `.load fts5` or `SELECT load_extension('fts5');`

Unfortunately, building FTS5 as a loadable extension does not solve the problem for `ogrinfo` or `ogr2ogr` that use sqlite3.dll.

There appears to be no way to enable extensions from within OGR (I get 'not authorized' errors when trying something like `SELECT load_extension('fts5')`.

The error from using `ogrinfo` that I get is: 

```
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(select * from search_list_full_text where search_text match '"car"*'):
  no such module: FTS5
```

I probably should have mentioned that use case when creating the issue.

Is it possible compile FTS5 support directly into the sqlite3.dll so it gets picked up by `ogrinfo` and `ogr2ogr`?

**Comment by jratike80** [comment]
It seems to work for me if I use the GDAL config option for loading the extension as documented in https://gdal.org/drivers/vector/gpkg.html

`ogrinfo polygon.gpkg -sql "CREATE VIRTUAL TABLE email USING fts5(sender, title, body)" --config OGR_SQLITE_LOAD_EXTENSIONS fts5`

Test and close the issue if it works also for you.

**Comment by rdewit** [comment]
@jratike80, that works for me too! Thanks so much. I can't believe I missed the `OGR_SQLITE_LOAD_EXTENSIONS` config option. Closing.
