### ISSUE TITLE
c# bindings: GDAL.Native package missing linux binaries

### ISSUE THREAD

**Issue by Gigas002** [gisinternals/buildsystem#189]
It’s good to see there’s some work being done for GDAL nuget packages. Could you please distribute the linux binaries with native package as well?
I’d suggest using [NetVips](https://www.nuget.org/packages/NetVips.Native/)-like approach on this, e.g. `GDAL.Native` package will contain `GDAL.Native.win-x64` and `GDAL.Native.linux-x64` dependencies. This way we don’t break existing `GDAL.Native` package users experience; the native package distributes all the natives and in case someone needs only one runtime can target different package as well.
Though I understand, how this can break existing folder structure, because binaries should be written the way not to override each other, e.g. `gdal/win-x64` and `gdal/linux-x64` instead of just `gdal/`, but I still think it's a good approach

**Comment by szekerest** [comment]
@Gigas002 That would require a linux build system, from where we could obtain the native dll-s in a reproducible way. GISInternals can provide only Windows binaries at the moment.

**Comment by szekerest** [comment]
Linux bins are not planned to be provided, closing
