### ISSUE TITLE
include pkgconfig files for proj, geos and perhaps others

### ISSUE THREAD

**Issue by shawnlaffan** [gisinternals/buildsystem#190]
Recent versions of Proj and GEOS  provide pkgconfig files and it would be useful if these were included in the dev releases under the lib/pkgconfig dir.  It would also be useful to have sqlite3, and probably any other .pc file that is generated.

The above assumes they are generated as part of the MSVC builds for each package, of course.

**Comment by szekerest** [comment]
geos only deploys .cmake files which has already been added.
Some other libs deploy .pc files which has also been added, closing
