### ISSUE TITLE
Visual Studio 2022 SDK

### ISSUE THREAD

**Issue by geographika** [gisinternals/buildsystem#195]
The VS2022 SDK is not listed at https://www.gisinternals.com/sdk.php but it is available from https://www.gisinternals.com/query.html?content=filelist&file=release-1930-x64-dev.zip - this may be intentional as perhaps it is not yet meant to be used?

The release builds all work fine, but I ran into a couple of issues when trying a debug build:

```
cmake -G "Visual Studio 17 2022" -A "x64" /mapserver -DCMAKE_BUILD_TYPE=Debug ...
cmake --build . --config Debug
```

It seems as though there may be an issue with `harfbuzz.lib`. I get the following errors:

```
harfbuzz.lib(harfbuzz.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in mapwms.obj [D:\MapServer\VS2022\build\mapserver.vcxproj]
```

and

```
harfbuzz.lib(harfbuzz.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in mapwms.obj [D:\MapServer\VS2022\build\mapserver.vcxproj]
```

The first was fixed by adding `_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH` under C/C++ >> Preprocessor >> PreprocessorDefinitions in the mapserver VS project as based on the answer here https://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt/29295896#29295896
However, I was unable to resolve the second. Does  `harfbuzz.lib` need regenerating with VS2022?

**Comment by szekerest** [comment]
@geographika All deps were compiled using the /MD setting. That cannot be mixed with /MDd. The closest cmake build containing debug info which would work is "RelWithDebInfo"

**Comment by geographika** [comment]
Thanks @szekerest - the following works perfectly. 

```
cmake -G "Visual Studio 17 2022" -A "x64" /mapserver -DCMAKE_BUILD_TYPE=RelWithDebInfo...
cmake --build . --config RelWithDebInfo
```

Then when debugging in Visual Studio `RelWithDebInfo` also needs to be selected (just to note I'd always used `Debug` with previous SDKs).

**Comment by szekerest** [comment]
Fixed https://www.gisinternals.com/sdk.php
