### ISSUE TITLE
Builds stopped 2022-03-19

### ISSUE THREAD

**Issue by jratike80** [gisinternals/buildsystem#196]
The latest developlemt builds are soon 4 weeks old, from 2022-03-19.

**Comment by szekerest** [comment]
There is a problem in the gdal version numbering scheme that prevents the python bdist packages from compiling

**Comment by szekerest** [comment]
Fixed in https://github.com/OSGeo/gdal/commit/00c5286b981129908d81f796980bf54e11d1411f
