### ISSUE TITLE
GDAL 3.6.0 version is available

### ISSUE THREAD

**Issue by rooby** [gisinternals/buildsystem#202]
I'm not sure how much work is involved or how much time it usually takes after a new release for it to go up on GISInternals, but the 3.6.0 version of GDAL is out now.

**Comment by rmaddu** [comment]
We are also looking for the 3.6.0 version of GDAL in GISInternals.

**Comment by rmaddu** [comment]
Any information about the availability of GDAL 3.6.0 packages in GISInternals?

**Comment by szekerest** [comment]
@rmaddu I'll try to set up a 3.6.2 build in this weekend.

**Comment by SureLeoo** [comment]
> @rmaddu I'll try to set up a 3.6.2 build in this weekend.

How is the 3.6.2 version going? thank you.

**Comment by szekerest** [comment]
complete, closing
