### ISSUE TITLE
Unworking net 6.0 SWIG-osgeo libraries after Windows 10 22H2(22H1) 19045.2130(19044.2130) version

### ISSUE THREAD

**Issue by GeorgGrebenyuk** [gisinternals/buildsystem#207]
Hello, I am getting a strange behaviour of osgeo binary data (for that https://www.gisinternals.com/query.html?content=filelist&file=release-1930-x64-dev.zip or that  binary release https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-dev.zip) on Windows 10 newer than 19045.2130 version.

In particulary:

Conbigs below are working:
- Windows 10 Pro 21H2 19044.1889;
- Windows 10 Pro 21H2 19044.1645;
- Windows 10 Pro 22H2 19045.2130;

Configs below are not working:
- Windows 10 Pro 22H2 19045.2604;
- Windows 10 Pro 22H2 19045.2251 (and with updates to 19045.2604)

I'm develop a c# (net 6.0) package for one of CAD system that use navive c++ PROJ api (myself PInvoke auxiliary library) and .NET API from OSGeo (swig in your releases); native c++ api (and functions on them) works well, but on SWIG I'm getting an errors such below:

> System.TypeInitializationException: The type initializer for 'OSGeo.OSR.OsrPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'osr_wrap' or one of its dependencies: Не найдена указанная процедура. (0x8007007F)
   at OSGeo.OSR.OsrPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Osr(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.OSR.OsrPINVOKE.SWIGExceptionHelper..cctor()

It's interesting: when I run application (plugin) even in Release-mode via Visual Studio 2022 all working correctly, but in manual-mode I'm getting a crash. 

I haven't any ideas whats happened in newer Windows updates and will be grateful you for any advice!

**Comment by szekerest** [comment]
@GeorgGrebenyuk Could you investigate that failure with process monitor (https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) which dll could not be loaded actually? It looks like one of the dependencies of osr_wrap.dll couldn't be found.

**Comment by GeorgGrebenyuk** [comment]
I'm already tested all problem cases with it and couldn't find anything of missing dlls ... besides one strange assembly:

`System.Windows.Forms.resources, Version=6.0.2.0, Culture=ru-RU, PublicKeyToken=b77a5c561934e089.dll` (because a frontend's part I doing with WinForms)

It's interesting, that if test on .NET Framework and released 1928 all works correctly, but if test with .NET Framework and reselase 1930 bug is coming  with "Dll not find".
There is not a problem for me, I've been wanting to to rewrite all code in native c++ API... there is an occasion to start it :)

Also I wanted to check same code but with original c++ api ... and I will publish results here after checking (to determine, if that problem dealing only with SWIG/.NET or it's a C++ dlls's and linking too...)

**Comment by szekerest** [comment]
@GeorgGrebenyuk Are you sure the required environment variables are also set when running in manual mode? I'd also suggest to check the nuget packages GDAL, GDAL.Native and GDAL.Plugins where a startup code is also provided to set the environment running GDAL properly.
If you create a simple console app that can reproduce this issue, I'd test that on the build server which is also 22H2 19045.2604

**Comment by GeorgGrebenyuk** [comment]
Hello, sorry for long-time pause; 
I have been tried run small project as console aplication in those windows versions and was not reproduced that error. So, I am tinking that error was dealing non with SWIG or OSGeo's code, but with software where my codes were loaded as plugin (It's Russian analogue of Autodesk AutoCAD, that migrated to .NET 6.0 and there a lot of little incopability cases).

So, that Issue can be closed as non dealing with OSGeo "stable packages". 
Sorry again for excess post.
