### ISSUE TITLE
gdal-3.7.2-1930-x64-core.msi requires proj_9_3.dll but only ships proj_9_1.dll

### ISSUE THREAD

**Issue by telephono** [gisinternals/buildsystem#219]
I use the GDAL core MSI package and GDAL Python 3.10 bindings in a Python project but since the release of GDAL 3.7.2, the Python bindings no longer work.

```python
from osgeo import gdal
```
Fails with:
```
ImportError: DLL load failed while importing _gdal: The specified module could not be found.
```

Apperently, the `gdal.dll` requires the `proj_9_3.dll` but the `gdal-3.7.2-1930-x64-core.msi` only ships with `proj_9_1.dll`

![Screenshot 2023-10-20 111312](https://github.com/gisinternals/buildsystem/assets/111712/f265c84a-c07b-4463-9802-e4a4c35ce596)

![Screenshot 2023-10-20 111429](https://github.com/gisinternals/buildsystem/assets/111712/7909ad08-b547-4aa7-896d-529279d57c23)

**Comment by szekerest** [comment]
Fixed
