### ISSUE TITLE
Dll Not Found When Compiling C# Project Self-Contained

### ISSUE THREAD

**Issue by Mbucari** [gisinternals/buildsystem#220]
When compiling the C# project Self-Contained, `GdalConfiguration` throws `DllNotFoundException` for gdal-wrap.dll. I've traced the problem to the following line in the `GdalConfiguration` static constructor:
```C#
string executingAssemblyFile = new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase).LocalPath;
```

The problem is that `AssemblyName.CodeBase` is null for Self-Contained applications. See error code [IL3000](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000).

As an alternative, Microsoft recommends using `System.AppContext.BaseDirectory`. Alternatively you may use `Environment.ProcessPath`.

**Comment by szekerest** [comment]
This issue is applied to the single file assemblies.
Fixed in the 3.7.3 nuget packages
