### ISSUE TITLE
Recent releases are missing the core msi installer

### ISSUE THREAD

**Issue by miccoh1994** [gisinternals/buildsystem#226]
e.g. https://gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-10-0-mapserver-8-2-2.zip

historically reported here https://github.com/gisinternals/buildsystem/issues/167

Interestingly the installer is present for win32 but not x64

**Comment by szekerest** [comment]
@miccoh1994 Just fixed the msi build issue
