### ISSUE TITLE
Console redirection fails with ECW plugin with MSVC >= 1400

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#36]
GDAL ticket http://trac.osgeo.org/gdal/ticket/5128  and thread http://lists.osgeo.org/pipermail/gdal-dev/2013-September/037066.html

My recent findings :

Hum, this is an interesting (=annoying) issue. Here's the result of my tests (only on 32 bit builds) :
- release-1600-gdal-1-10-mapserver-6-2 : bad
- release-1600-gdal-1-9-1-mapserver-6-0-3 : bad
- release-1400-gdal-mapserver (latest dev version): bad
- release-1500-gdal-mapserver (latest dev version): bad
- release-1400-gdal-1-8-1-mapserver-6-0-1 : bad
- release-1310-gdal-mapserver (latest dev version): ... good ...
- release-1310-gdal-1-8-1-mapserver-6-0-1 : good

So my conclusion is that it does not depend on the GDAL version, but it does depend on the MSVC compiler. And apparently only MSVC 1310 pleases the ECW SDK. The issue must be a bad interaction between the old ECW SDK 3.3 code and MSVC >= 1400.

**Comment by szekerest** [comment]
ECW was upgraded, not sure about the status of the issue. Closing for now.
