### ISSUE TITLE
Requires Windows 8?

### ISSUE THREAD

**Issue by lumberg72** [gisinternals/buildsystem#57]
Hi,
I'm on 64 bit Windows 7 and trying to use Java Mapscript from the following download...
release-1600-x64-gdal-1-10-mapserver-6-4.zip

Java keeps complaining that it cannot find some dependencies for javamapscript.dll (but doesn't reveal which ones). As far as I can tell, I've got all the necessary Mapserver DLL's in place, etc.  I also confirmed that I have the latest vc 2010 redistributable package. Eventually I resorted to Dependency Walker to see what else it might need.

Dependency Walker tells me that the following DLL's are missing.  

API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

After a little looking around, it seems that the bulk of these are specific to Windows 8 and not available on Win 7. So I am guessing that this was built on Win 8 and will require Win 8. Is that correct?  Any suggestions for Win 7?

Thanks!

**Comment by szekerest** [comment]
One requirement is to install the 64 bit version of JRE/JSE on the system to have the 64 bit versions of the java bindings work.
