### ISSUE TITLE
_gdal_array.pyd is missing for python 3.3 in MSVC2010 (Win64) -development

### ISSUE THREAD

**Issue by mlt** [gisinternals/buildsystem#58]
Somehow the following msi misses that :(

http://www.gisinternals.com/sdk/Download.aspx?file=release-1600-x64-gdal-mapserver\GDAL-1.10.0.win-amd64-py3.3.msi

py3.2 has it once unpacked with msiexec /a, but that is not the python version I have installed.

Is there a build log for python specific version? I see only generic log for megabundle tailored for 2.7

**Comment by szekerest** [comment]
This appears to be fixed in the recent SDK
