### ISSUE TITLE
Add support for OGDI

### ISSUE THREAD

**Issue by szekerest** [gisinternals/buildsystem#6]

**Comment by sylvaneau** [comment]
Hi,

It would be amazing to include support for OGDI. I built my own version of GDAL from sources, and the following code is enough to enable this format (to be added in `nmake.local` or `nmake.opt` depending on the way you build gdal) :

```
OGDIDIR = C:\OSGeo4W64
OGDI_INCLUDE = $(OGDIDIR)\include\ogdi
OGDIVER = 41
OGDILIB = $(OGDIDIR)\lib\ogdi.lib $(OGDIDIR)\lib\zlib.lib
```

OGDI binaries are availables from OSGeo4W64.

If I can help in any way, feel free to ask, I can submit a merge a request if you gide me through your repo a little bit.

Regards

**Comment by szekerest** [comment]
Working on a completely new build configuration where the dependencies are updated to the latest versions. OGDI has already be added there, but I'll require to spend some additional time to make that build sufficient for releasing. Hopefully I can achieve that result in this month.

**Comment by sylvaneau** [comment]
Just amazing ! Thx a lot !

**Comment by szekerest** [comment]
OGDI is now included in the VS2019 builds, closing.
