### ISSUE TITLE
Builds ship with openssl 1.01f, which is subject to "Heartbleed" vulnerability

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#60]
According to http://heartbleed.com/ : "OpenSSL 1.0.1 through 1.0.1f (inclusive) are vulnerable"

**Comment by odavidbrito** [comment]
Hi,

According to 
https://www.openssl.org/news/secadv/20160922.txt

OpenSSL 1.0.1 users should upgrade to 1.0.1u
and current GDAL 2.3.1 uses OpenSSL 1.0.1h.

Are there any plans to upgrade? Even for newer versions of OpenSSL too keep up with vulnerabilities found?


Thanks for the good work!

David
