### ISSUE TITLE
Update Libs (FileGDB, OCI, PCRE, PostgreSQL, DWG, Xerces-c)

### ISSUE THREAD

**Issue by zer0infinity** [gisinternals/buildsystem#62]
- FileGDB_API_VS2010_1_3 (http://www.esri.com/apps/products/download/index.cfm?fuseaction=download.main&downloadid=845)
- instantclient-basic-nt-12.1.0.1.0, instantclient-sdk-nt-12.1.0.1.0 (http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html)
- pcre-7.0-lib, pcre-7.0-bin (http://sourceforge.net/projects/gnuwin32/files/pcre/7.0/)
- postgresql-9.3.4-3-windows-binaries (http://www.enterprisedb.com/products-services-training/pgbindownload)
- TX_SDK_3.09.1.0 (file is removed, it was here: http://oda1.opendesign.com/download/index.php?file=15)
- xerces-c-3.1.1-x86-windows-vc-10.0 (http://xerces.apache.org/xerces-c/download.cgi)

Successful compiled with gdal 1.11 and MSVC 2010 Pro (x86 and x64).

edit: add links.

**Comment by szekerest** [comment]
The VS2019 packages contain the most recent libs
