### ISSUE TITLE
MapCache

### ISSUE THREAD

**Issue by rnonhebel** [gisinternals/buildsystem#68]
Hello, is it possible that you can compile the MapCache for Windows as well?

**Comment by szekerest** [comment]
mapcache binaries added to the recent SDK builds, closing

**Comment by geographika** [comment]
Excellent news! Many thanks @szekerest

**Comment by szekerest** [comment]
@geographika I wonder if I could create a ready to use solution to utilize mapcache/mapserver in IIS. Let me know if you have experiences in the configuration/deployment

**Comment by geographika** [comment]
I have a working MapCache on IIS server using GISInternal DLLs and a  `mapcache.fcgi.exe` built using the process at https://github.com/MapServer/mapcache/blob/main/appveyor.yml

There were issues around setting `PATH_INFO` that I used https://www.iis.net/downloads/microsoft/url-rewrite to resolve. I have the following `web.config` for a web application at http://localhost/mapcache

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<handlers>
			<add name="mapcache" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\MapCache\bin\mapcache.fcgi.exe" resourceType="Unspecified" requireAccess="Script" />
		</handlers>			 
   
        <!-- need below or "received wms with no service and request" -->
        
        <!-- need to add PATH_INFO to allowed server variable list -->
        
		<rewrite>
			<rules>
				<rule name="AddPathInfo">
					<match url=".*" />
					<serverVariables>                        
						<set name="PATH_INFO" value="{C:1}" />
					</serverVariables>
					<conditions>
						<add input="{PATH_INFO}" pattern="/mapcache/demo/(.*)" />
					</conditions>
				</rule>
			</rules>
		</rewrite>

	</system.webServer>        
</configuration>

```

I have some more notes on the reasons/setup somewhere so will add them to this issue when I find them. 

Also in the applicationHost, or in the web.config I have the following block:

```xml
	<!-- https://www.iis.net/configreference/system.webserver/fastcgi -->
	<fastCgi>
	   <application fullPath="C:\MapCache\bin\mapcache.fcgi.exe" arguments="" maxInstances="4" idleTimeout="300" 
	   activityTimeout="30" requestTimeout="90" instanceMaxRequests="10000" protocol="NamedPipe" flushNamedPipe="false">
			 

		  <environmentVariables>
			 <environmentVariable name="MAPCACHE_CONFIG_FILE" value="C:\MapCache\services.xml" />
		  </environmentVariables>
	   </application>
	</fastCgi>
```
