### ISSUE TITLE
No module named '_gdal_array'

### ISSUE THREAD

**Issue by chau-intl** [gisinternals/buildsystem#70]
I have been able to use the previous GDAL builds from here, but the following build gives me the error **No module named '_gdal_array'**:

MSVC2010 (Win64) -stable (release-1600-x64-gdal-1-11-mapserver-6-4):
- gdal-111-1600-x64-core.msi
- GDAL-1.11.0.win-amd64-py3.3.msi

The problem might be related to this issue: https://github.com/gisinternals/buildsystem/issues/58

**Comment by chau-intl** [comment]
Returning to this issue, I can see, that each `GDAL-1.11.1.win-xxx-py3.3.msi` no matter which *MSVC* is used, has a size smaller than its previous versions `py3.1` and `py3.2`. This could indicate that something is missing from the file.

**Comment by szekerest** [comment]
This appears to be fixed in the recent SDK
