### ISSUE TITLE
Upgrade ECW/JP2 SDK from 5.0 to 5.1.

### ISSUE THREAD

**Issue by lpinner** [gisinternals/buildsystem#71]
Version 5.1 of the ERDAS ECW/JP2 SDK was released earlier this year and contains a number of bugfixes and enhancements over 5.0 

http://download.intergraph.com/downloads/erdas-ecw-jp2-sdk-v5.1

Would you be able to upgrade the version that the GIS Internals GDAL ECW/JP2 plugin is built against?

Regards
Luke

**Comment by lpinner** [comment]
Thank you Tamas

**Comment by szekerest** [comment]
I've been informed about that the v5.2 release coming in the next week or two which adds VC120 and various other performance improvements
