### ISSUE TITLE
CMake missing and build failure for Win7 x64

### ISSUE THREAD

**Issue by PhilAnzel** [gisinternals/buildsystem#79]
Tamas,

I'm encountering an early fatal error when building MapServer. I'm running on a Windows 7 x64 platform with VS2013 installed.

I downloaded release-1800-x64-dev.zip and release-1800-x64-gdal-mapserver-src.zip on 25-Mar-2015 and unzipped as suggested by the readme.txt to D:\mapserver70sdk. The VS2013 command shell environment was established with:
 %comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat""

The overall Makefile references CMake version 2.8.12.1. This version is not included in your SDK distribution files, I downloaded current version 3.2.1 in its place..

No errors were encountered when building gdal:
    nmake gdal-csharp DEBUG

There were problems building Mapserver:
  nmake ms ^
    DEBUG^=YES ^
    MS_DIR^=mapserver ^
    CMAKE_DIR^=D:\mapserver70sdk\cmake-3.2.1-win32-x86 ^
      > nmake_ms_04.log 2>&1

There was an initial error which may not have been fatal:
-- Performing Test HAVE_SYNC_FETCH_AND_ADD
-- Performing Test HAVE_SYNC_FETCH_AND_ADD - Failed
CMake Warning (dev) at CMakeLists.txt:250 (add_library):
  Syntax error in cmake code when parsing string
    D:\mapserver70sdk\regex-0.12/regex.c
  Invalid escape sequence \m

There was a final fatal message reported:
-- Will install files to C:/Program Files/MapServer
-- Will install libraries to C:/Program Files/MapServer/lib
-- Configuring incomplete, errors occurred!
See also "D:/mapserver70sdk/mapserver/vc12x64/CMakeFiles/CMakeOutput.log".
See also "D:/mapserver70sdk/mapserver/vc12x64/CMakeFiles/CMakeError.log".
NMAKE : fatal error U1077: 'D:\mapserver70sdk\cmake-3.2.1-win32-x86\bin\cmake.EXE' : return code '0x1'
Stop.

Is there a problem with a CMake version mismatch? How should I proceed?

Thanks.
Phil Anzel (phil.anzel@ftc.usda.gov)

**Comment by szekerest** [comment]
I should indeed make the build setup more fault tolerant.

I've tried you setup and it seems to work with cmake 3.2.1 too. I have used "VS2013 x86 Native Tools Command Prompt" from Microsoft Visual Studio 12.0\Common7\Tools\Shortcuts

Actually you can eliminate the regex warning by adding REGEX_PATH to the command line using forward slashes such as:

nmake ms DEBUG=1 MS_DIR=mapserver CMAKE_DIR=E:\mapserver7sdk\cmake-3.2.1-win32-x86 REGEX_PATH=E:/mapserver7sdk/regex-0.12

But you should also edit the ms-cmake target in the Makefile by disabling all the unused options DWITH_PYTHON=0 -DWITH_JAVA=0  etc.

**Comment by PhilAnzel** [comment]
Thanks Tamas. I'll try your suggestions, especially disabling unused options. - Phil
