### ISSUE TITLE
ORACLE option ignored and possible Mono dependency

### ISSUE THREAD

**Issue by PhilAnzel** [gisinternals/buildsystem#80]
Hi Tamas,
Starting with release-1800-x64-dev.zip and release-1800-x64-gdal-mapserver-src.zip I'm running into two problems with the "ms" build operation on Windows 7:

1. In the ms-cmake target (Makefile line 2836) there is the explicit option setting "-DWITH_ORACLESPATIAL=0". CMake appears to ignore this. If I execute the command:
  nmake ms ^
    DEBUG^=YES ^
    INSTALL_DIR=d:\INSTALL_DIR ^
    MS_DIR^=mapserver ^
    CMAKE_DIR^=d:\mapserver70sdk\cmake-3.2.1-win32-x86 ^
    REGEX_PATH^=d:/mapserver70sdk/regex-0.12 ^
    WITH_ORACLESPATIAL^=0 ^
      > nmake_ms_11.log 2>&1
the log file shows the lines:
ORACLE_HOME=Oracle\instantclient_12_1-x64
-- Could NOT find ORACLE (missing:  ORACLE_LIBRARY) 
CMake Error at CMakeLists.txt:51 (message):
  ORACLESPATIAL library/component/dependency could not be found.
    HINTS:
    - disable ORACLESPATIAL support by adding -DWITH_ORACLESPATIAL=0
What else should be done to skip over attempts to access the nonexistent Oracle directory?

2. The same Makefile line references "pkg-config.exe":
"-DPKG_CONFIG_EXECUTABLE=C:\Program Files (x86)\Mono\bin\pkg-config.exe"
Does Mono need to be installed, or is there another option available?

Thanks
- Phil Anzel phil.anzel@ftc.usda.gov

**Comment by PhilAnzel** [comment]
Tamas,

I solved the first problem by editing the command line in Makefile in the ms-cmake target, explicitly setting "-DWITH_ORACLE_PLUGIN=0". The build ran successfully.

The second problem, reliance upon pkg-config.exe, is a mystery: I do not have Mono installed on my notebook yet the build ran without error. Is the pkg-config.exe therefore not required?

Thanks.

- Phil

**Comment by szekerest** [comment]
added detection capabilites for oracle python and java in the makefile
