### ISSUE TITLE
Update sqlite lib

### ISSUE THREAD

**Issue by JPA2015** [gisinternals/buildsystem#81]
Using something like:
  ogrinfo myfile.sqlite -sql "SELECT sqlite_version()"
I can see that the GDAL builds from gisinternals use sqlite version 3.7.9.

In comparison the builds from OSGeo4W use sqlite version 3.7.17 and the newest sqlite version is 3.8.9.

Problem: when a spatialite DB was created with a newer sqlite version then it can not be written with GDAL from gisinternals. Using the API I then get an error 6 ("CreateFeature : unsupported operation on a read-only datasource"). It might come from the fact that starting with version 3.7.10 of sqlite, the default schema format number was changed from 1 to 4.
Anyway it would be nice if the else excellent builds from gisinternals would use a newer version of sqlite.

**Comment by pmeems** [comment]
We use these binaries with MapWindow GIS and some of our users have SpatiaLite database made with v4. GDAL can open them, but cannot edit them and reports this debug msg: "SpatiaLite v4 DB found, but updating tables disabled because runtime spatialite library is v3.0 !"
It would be nice if you could also support v4 SpatiaLite files.

**Comment by szekerest** [comment]
Thank you, I'll update the version shortly

**Comment by pmeems** [comment]
I know you are very busy and you are already doing a great job, but we use your binaries with MapWindow5 and lots of our users use SpatiaLite v4 files which we cannot support until you support it.
Can you give us some indication when this issue will be executed?

Thanks, Paul

**Comment by pmeems** [comment]
We're still very curious when this will be implemented. One of our team members has send you the changes needed to include SpatiaLite v4. It seems a small change.

**Comment by szekerest** [comment]
Fixed

**Comment by pmeems** [comment]
I can confirm with the package we can now open SpatiaLite v4 files.
Thanks for this.
