### ISSUE TITLE
Daily builds no longer build

### ISSUE THREAD

**Issue by rouault** [gisinternals/buildsystem#82]
Hi Tamas,

I've notices GISInternals builds are not refreshed since a few days. 

There's a curl problem reported in http://build.gisinternals.com/sdk/build-output/vc8-20150623-1-10-03-06-vc8-dev-err.txt

**Comment by szekerest** [comment]
Yes, there has been a networking problem. I hope that was solved today.

**Comment by rouault** [comment]
Works again
