### ISSUE TITLE
MSVC 2015 builds?

### ISSUE THREAD

**Issue by jumpinjackie** [gisinternals/buildsystem#84]
Are there plans for MSVC 2015 builds of GDAL/OGR?

**Comment by szekerest** [comment]
yes, it is in my TODO list in the next 1-2 months.

Best regards,

Tamas


2015-09-04 9:32 GMT+02:00 Jackie Ng <notifications@github.com>:

**Comment by aletricks** [comment]
Any news for MSVC 2015 builds?

**Comment by pmeems** [comment]
Microsoft seems to discontinue the VS community 2013 software.
When can we expect the MSVC 2015/2017 builds?

**Comment by jumpinjackie** [comment]
If anyone wants MSVC 2015 builds of GDAL/OGR, your current best bet is to try https://github.com/Microsoft/vcpkg and use it to builds its gdal port (currently 1.11.3).

vcpkg works with VS 2015 Update 3 and VS 2017

Just be warned that the gdal vcpkg port is not as fully featured as the one produced by the gisinternals buildsystem. It's currently only standard configuration with GEOS support.

**Comment by rouault** [comment]
@szekerest You can know close this issue now that you provide MSVC 2015 & 2017 builds
