### ISSUE TITLE
GDAL Python 2.7 bindings does not support MrSID

### ISSUE THREAD

**Issue by theej** [gisinternals/buildsystem#85]
Hello,

This issue is part of my original question that I asked on GIS StackExchange here: http://gis.stackexchange.com/a/164288
The issue remains unsolved.

As described in the solution, I installed GDAL core, MrSID plugin and GDAL Python 2.7 bindings from GISInternals. Unfortunately, MrSID is not supported when I use the Python binding for GDAL. When I try to read a MrSID file in Python, I get this error:

ERROR 4: `my_file.sid' not recognised as a supported file format.
Could not open image

Indeed, the list of supported raster formats by gdal in Python does not contain MrSID. The list of supported raster formats by gdal itself does support MrSID. The Python binding does not seems to be aware of the installation of the MrSID plugin.

Is this a known issue? What can I do to fix this? Thanks.

Joeri

**Comment by szekerest** [comment]
The GDAL_DRIVER_PATH environment variable should be set to that location where the MrSID plugin dll exists.
