### ISSUE TITLE
gdal_utils.h is missing

### ISSUE THREAD

**Issue by pmeems** [gisinternals/buildsystem#86]
We would like to use the new librarified tools of GDAL v2, but we're missing gdal_utils.h.
Could you add it to your package?

**Comment by pmeems** [comment]
Any change of adding this header file soon?
With MapWindow we want to use the tools as C callable functions as mentioned here http://www.gdal.org/gdal__utils_8h.html#a057aaea8b0ed0476809a781ffa377ea4
But we need this header file.

**Comment by szekerest** [comment]
Fixed

**Comment by pmeems** [comment]
I can confirm the file is added to the package. Thanks!
