### ISSUE TITLE
Python 3.43 _gdal_array.pyd missing?

### ISSUE THREAD

**Issue by apiszcz** [gisinternals/buildsystem#87]
MSVC 2013   x64 release-1800-x64-gdal-mapserver information 2015-11-24 15:09:11 e7b6ed2 r31745

I am unable to locate _gdal_array.pyd for Python 3.4, I do not see it the separate python msi either.
GDAL-2.1.0.win-amd64-py3.4.msi.

This is the associated stack track. The
The .py file exists in gdal\python, but no .pyd

Traceback (most recent call last):
  File "C:\p\v1\lib\gdal210d\bin\gdal_calc.py", line 46, in <module>
    from osgeo import gdalnumeric
  File "C:\p\v1\lib\gdal210d\bin\gdal\python\osgeo\gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "C:\p\v1\lib\gdal210d\bin\gdal\python\osgeo\gdal_array.py", line 26, in <module>
    _gdal_array = swig_import_helper()
  File "C:\p\v1\lib\gdal210d\bin\gdal\python\osgeo\gdal_array.py", line 18, in swig_import_helper
    import _gdal_array
ImportError: No module named '_gdal_array'

**Comment by Aspirisha** [comment]
So, have anyone solved the issue?

**Comment by apiszcz** [comment]
Unsure, I moved to python 3.5. Now I await the 3.5 binding.

**Comment by Shot2** [comment]
There is (at the moment) no working combination allowing recent gdal-amd64 + functional python tools. Use win32 builds maybe...

**Comment by Aspirisha** [comment]
Thanks for the replies, guys. For it really took me the whole day to look for it. You know, I just really wondering what was the reason not to put that dll into distribution... Yet, probably it's possible to compile the bastard manually?

**Comment by szekerest** [comment]
This will require to set up numpy for all python bindings. 
I'll try to fix these issues in the weekend as well as to upgrade to the latest python versions

**Comment by apiszcz** [comment]
If possible while you are in looking around, a look into the bindings for
Python 3.5 / 64 bit would be appreciated. Thank you.

**Comment by Aspirisha** [comment]
> This will require to set up numpy for all python bindings. 
I'll try to fix these issues in the weekend as well as to upgrade to the latest python versions

Well, that will be great! Meanwhile I'll try to manage it compiling with visual studio 2010 x64 compiler. 
Can you tell me, what is required to produce python bindings with it? I see there is nmake.opt, and there are few lines about py. Is it enough to properly set PYDIR locating to the python directory and uncommenting the line with HAVE_NUMPY=1 (for I already have numpy installed)? I mean, if I run 
`namke /f makefile.vc`, will it be ok?

**Comment by chau-intl** [comment]
@szekerest, were you successful in fixing this issue or did you run into other obstacles along the way?

Fixing this issue should also fix #58 and #70 and that would be REALLY nice :)

**Comment by apiszcz** [comment]
So unfortunately I do not have the time to build the systems. I asked
Gothke to build GDAL and he did and it works for Python 3.5, I also asked
for LIBKML support which added recently. It would be ideal to have another
Windows BUILD site for Windows Python 3.5 bindings, esp for GDAL 2.1dev or
2.1.

REF: http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by szekerest** [comment]
This appears to be fixed in the recent SDK
