### ISSUE TITLE
GDAL-2.0.0.win-amd64-py2.7.msi is missing

### ISSUE THREAD

**Issue by Guts** [gisinternals/buildsystem#90]
[Here](http://www.gisinternals.com/query.html?content=filelist&file=release-1500-x64-gdal-mapserver.zip) it's possible to download GDAL-2.1.0.win-amd64-py2.7.msi but not the 2.0.1 version. It would not be an issue if the 2.1.0 core version should be available gdal-2.1.0-1500-x64-core.msi

**Comment by szekerest** [comment]
In fact gdal-201-1500-x64-core.msi  corresponds to GDAL 2.1.x
