### ISSUE TITLE
gzdirect function is missing in zlib1.dll

### ISSUE THREAD

**Issue by Rungee** [gisinternals/buildsystem#91]
In my application, I am using the latest build of [mod_spatialite](http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/) library.  When I try to load this extension in sqlite connection, I get the following exception
"The procedure entry point gzdirect could not be located in the dynamic link library zlib1.dll"
It looks like gisinternals/buildsystem uses an old version of zlib library, which misses gzdirect function.

**Comment by szekerest** [comment]
zlib has already been updated
