### ISSUE TITLE
PDF support missing in GDAL 2.1

### ISSUE THREAD

**Issue by AEMPhil** [gisinternals/buildsystem#96]
Fresh install of GDAL 2.1 from release-1800-x64-gdal-2-1-0-mapserver-7-0-1 [core msi](http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-1-0-mapserver-7-0-1/gdal-201-1800-x64-core.msi) doesn't seem to have GeoPDF support; it is not listed by gdalinfo --formats

Was it intentionally removed or am I doing something wrong?

**Comment by szekerest** [comment]
At the moment you should chose one of the daily built packages which contain GeoPDF support enabled.

**Comment by AEMPhil** [comment]
Indeed, that worked. Thanks for the assistance, and more importantly for maintaining all those packages!
