### ISSUE TITLE
Can't run gdal_calc.py on Windows 64bit

### ISSUE THREAD

**Issue by ivopavlik** [gisinternals/buildsystem#99]
I installed GDAL with Python extensions to my Windows machine by this tutorial: https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows (you can see there my comment). I need to use gdal_calc.py. When I install 32bit version, it works as expected (even though I need to install numpy module to Python). But when I try to install 64bit version, gdal_calc.py fails with error:

```
Traceback (most recent call last):
File “C:\Program Files\GDAL\gdal_calc.py”, line 50, in
from gdalnumeric import *
ImportError: No module named gdalnumeric
```

I use:
Windows10 64bit
Python 2.7.12 (64bit)
GDAL 1.11.4 (installed via gdal-111-1500-x64-core.msi)
Python bindings installed via GDAL-1.11.4.win-amd64-py2.7.msi
Environment variables connected with Python and GDAL:

```
PATH=C:\Python27;C:\Python27\Scripts;...C:\Program Files\GDAL
GDAL_DATA=C:\Program Files\GDAL\gdal-data
GDAL_DRIVER_PATH=C:\Program Files\GDAL\gdalplugins
```

I also tried to install different 64bit versions of Python/GDAL, but with no success.

Thanks.

**Comment by szekerest** [comment]
This appears to be fixed in the recent SDK
